apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      nodeSelector:
        storage: ssd
        env: prod
      containers:
      - name: nginx
        image: nginx
        
        ports:
        - containerPort: 80
