---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
# these toleration will be applied to only those node which have taints defined by command:- kubectl taint nodes {node name} storage=ssd:NoSchedule | storage=ssd:PreferNoSchedule | storage=ssd:NoExecute
      tolerations:
        - key: "storage"
          operator: "Equal"
          value: "ssd"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

# If taint helps to segregate the workloads of pods then why there is a namespace? When to use namespace and taints-and-tolerations?

# Taint works on node and toleration works on pod

# kubectl taint node {node-name} storage=ssd:NoSchedule