apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
# If you run kubectl run {pod_name} -l app=nginx --image=nginx and then apply this file then extra pods created by replicationset from this file will just be 2
# Because controller will look at the exact labels dictionary value if desired state exists then it will not create any extra on top of it
  replicas: 3
  selector:
   matchExpressions:
  # If you add another key value in selector along with template.metadata.labels then it will create another 3 replicas as now labels consists of two key-value pairs
    - key: app
      operator: In
      values:
      - nginx
      - apache

  #  If you uncomment the below environment key line but keep it in your template.metadata.labels then the file will just look for the creation of replicas with labels just app=nginx. Go ahead and try it
  #  environment: development
  template:
    metadata:
      labels:
        app: nginx
        environment: development
    spec:
      containers:
        - name: nginx-container
          image: nginx

# If I use kubectl set image (deployment, rc, rs) {object_name} pod-name=image-name then deployment does not rollout these changes to existing pod with updated image; only new pod get the new update. Same applied to RC, and RS