apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-demo
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz               # Endpoint to check for health status
        port: 8080                  # Port where the application is running
        httpHeaders:
        - name: Custom-Header       # Custom header name
          value: Awesome            # Custom header value
      initialDelaySeconds: 3        # Wait 3 seconds before starting probes
      periodSeconds: 3              # Run the probe every 3 seconds
      timeoutSeconds: 1             # Wait 1 second for a response before timing out
      failureThreshold: 1           # After 1 failure, restart the container


# Expected Outcome of this config:

# For the first 10 seconds after the container starts, the /healthz endpoint returns a status of 200, indicating success.
# After 10 seconds, the /healthz endpoint returns a status of 500, indicating failure. This is how the application in the container is configured
# The liveness probe detects the failure and restarts the container.
# This cycle repeats, with the container running for 10 seconds before being restarted.