apiVersion: v1
kind: Pod
metadata:
 name: readiness-demo
spec:
 containers:
   - name: busybox-app
     image: busybox
     command: ["sh", "-c", "touch /tmp/ready; sleep 3600"]
     readinessProbe:
      exec:
        command: ["cat", "/tmp/ready"]
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1