apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-demo
spec:
  containers:
  - name: tcp-app
    image: ubuntu:latest
    command:
      - sh
      - -c
      - |
        apt update && \
        apt install -y netcat-openbsd && \
        nc -l -p 9444 && \
        sleep 3600
    startupProbe:
      tcpSocket:
        port: 9444            # Checks TCP server accessibility on port 9444
      failureThreshold: 15    # Allows up to 15 failed attempts
      periodSeconds: 5        # Probe runs every 5 seconds