# First check if the metrics server is installed or not. If not then get into metric-server-api.yaml in limits-and-request folder and apply it
# To apply this config first get into autoscaler/vertical-pod-autoscaler and then execute ./hack/vpa-up.sh to download the VPA components. Later, to uninstall do ./hack/vpa-down.sh in same folder

apiVersion:  autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
 name: nginx-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       nginx-deploy
  updatePolicy:
   # updateMode options:
    # "Off"     - VPA only recommends resources, does NOT apply them.
    # "Initial" - VPA sets recommended resources at pod creation, no changes after.
    # "Auto"    - VPA automatically updates resources and restarts pods as needed.
    updateMode: "Auto"