apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  # a namespace to create a service in that namespace to maintain organisation, isolation and security
  namespace: app1-ns
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 9090
    targetPort: 5678

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: app1-ns
spec:
  replicas: 3
  selector:
   matchLabels:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
     containers:
      - name: backend-container
        image: hashicorp/http-echo
        args:
          - "-text= Hello from Backend"