apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
   app: nginx
   environment: development
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
       - containerPort: 80
    - name: sidecar-container
      image: nginx
      args: ["sleep", "3600"]