apiVersion: v1
kind: Pod
metadata:
  name: cap-container
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
        add:
        - NET_ADMIN
        - SYS_TIME
