apiVersion: v1
data:
  DB_PASSWORD: Wm5KdmJuUmxibVJ3WVhOeg==
  DB_USER: Wm5KdmJuUmxibVIxYzJWeQ==
kind: Secret
metadata:
  creationTimestamp: "2026-06-11T23:15:22Z"
  name: frontend-secret
  namespace: default
  uid: a4bd91eb-4abd-4cde-ab92-96f7bde642af
type: Opaque
