apiVersion: v1
kind: Pod
metadata:
  name: emptydir-example
spec:
  volumes:
  - name: temp-storage
    emptyDir: {}
  containers:
  - name:  emptydir-example
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: temp-storage
